Removed Migrator code
Yorubaname/YorubaNameDictionary pull request #61
Opened 2024-07-18 20:15 UTC by Olusheenor

2024-07-18 20:30 UTC, Zifah requested changes

2024-07-18 20:30 UTC, Zifah commented on Api/Controllers/MigratorController.cs
I'm not a fan of having commented-out code in the codebase.

How about we just return OK from the controllers with a message instead?

2024-07-19 16:30 UTC, Olusheenor commented on Api/Controllers/MigratorController.cs
Ok.. Since we already throwing exceptions can leave the controllers

2024-07-19 16:59 UTC, Zifah approved these changes

2024-07-19 17:12 UTC, merged